### PR TITLE
Fix osx build

### PR DESCRIPTION
**Pull request by YoYuUm**
After changing that line it builds in osx without problems.

### CODE REVIEW

**Comment by zweicoder** [comment]
Thanks! Sadly I still won't be able to pack an OSX build to put under releases as I'm running Windows :(

**Comment by YoYuUm** [comment]
@zweicoder Is there any way I can help you submitting the dmg I just built?

**Comment by zweicoder** [comment]
@YoYuUm Add it to the `v 2.0.0` release or just drop it here if possible! Thanks!

**Comment by YoYuUm** [comment]
I don't think I have rights to add files to that release, so I attach it here:
http://www.fileconvoy.com/dfl.php?id=gc5a143bdcc2e91619997443744d17581302c39a45

**Pull request merged**
